version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18_prod_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - odoo18_prod_net

  odoo:
    image: odoo:18
    container_name: odoo18_prod
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./data/filestore:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo18_prod_net

networks:
  odoo18_prod_net:
    driver: bridge